version: "3"
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring-boost
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
