logging:
  level:
    org.springframework.web: info
spring:
  aot:
    enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
helpers:
  async:
    rejected-execution: java.util.concurrent.ThreadPoolExecutor.CallerRunsPolicy.class
    pool-name-prefix: "spring-boot-curd-example"
    preheat: true
