logging:
  level:
    org.springframework.web: info
spring:
  aot:
    enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:default
helpers:
  async:
    rejected-execution: java.util.concurrent.ThreadPoolExecutor.CallerRunsPolicy.class
    pool-name-prefix: "spring-boot-curd-example"
    preheat: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
    jmx:
      exposure:
        include: "*"
  jmx:
    metrics:
      export:
        enabled: true
  appoptics:
    metrics:
      export:
        enabled: true
china:
  region:
    enableProvinces: true