spring:
  security:
    user:
      password: 123456
      name: user
      roles:
        - admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  boost:
    authentication:
      debug: true
      permit:
        - pattern: /auth/register
          method:
            - GET
        - pattern: /actuator/**
          method:
            - GET
    fs:
      local:
        configs:
          - qualifier: 'default'
            path: /Users/daiyuang/
            type: LOCAL
          - qualifier: 'memory'
            path: 'file:///Users/daiyuang/Documents'
            type: MEMORY
logging:
  group:
    boost: org.spring.boost
  level:
    boost: TRACE
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

