logging:
  level:
    org.springframework.core.env: debug
    org.springframework.jdbc.**.*: debug
spring:
  shell:
    history:
      enable: true
  main:
    allow-bean-definition-overriding: true
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      maximum-pool-size: 10