const val IMPLEMENTATION = "implementation"
const val TEST_IMPLEMENTATION = "testImplementation"
const val COMPILE_ONLY = "compileOnly"
const val ANNOTATION_PROCESSOR = "annotationProcessor"
const val plantUMLSuffix = "puml"
const val JAKARTA = "jakarta"