spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
#    username: root
#    password: root
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  #      jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
#      driver-class-name: com.mysql.cj.jdbc.Driver
  authentication:
    debug: false
    permit:
      - pattern: "/actuator/**"
      - pattern: "/instances"
      - pattern: "/applications"
  threads:
    virtual:
      enabled: true
  mapping:
    source:
      code:
        debug: true
#  authentication:
#    permit:
#      - pattern: /actuator
#        method:
#          - GET
server:
  port: 8080
logging:
  level:
    org.toolkit.**.*: debug
    org.springframework.security: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true