spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 10000
        dialect: org.hibernate.dialect.MySQLDialect
